from lib.log import log

log.error('testing')